version: '3.1'

services:

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - '27018:27017'
    restart: always
    volumes: 
      - ~/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass