name: build

on:
  push:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  windows-build:
    runs-on: windows-2022
    strategy:
      matrix:
        dotnet-version: ['6.0.413']
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET CORE SDK ${{matrix.dotnet-version}}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Create manifest
        run: dotnet new tool-manifest
      - name: Run the build script
        shell: pwsh
        run: .\scripts\Build.ps1 --target=Build
      - name: Run tests
        shell: pwsh
        run: .\scripts\Build.ps1 --target=RunTest

