name: test

on:
  workflow_run:
    workflows: ["build"]
    branches: [master]
    types: 
      - completed

jobs:
  windows-test:
    runs-on: windows-2022
    strategy:
      matrix:
        dotnet-version: ['6.0.413']

    steps:
      - uses: actions/checkout@v3
      - name: Create manifest
        run: dotnet new tool-manifest
      - name: Run tests
        shell: pwsh
        run: .\Build.ps1 --target=RunTest